app:
  # build with Dockerfile
  dockerfile: ./.docker/containers/app/Dockerfile

  # sources environment variable configuration for our app
  env_file: ./docker/docker-application.env

  # use the Dockerfile next to this file
  build: .

  volumes:
    - ./app:/home/app

  # expose the port we configured Puma to bind to
  ports:
    - "4545"

# service configuration for our web server
web:
  # build with Dockerfile
  dockerfile: ./.docker/containers/web/Dockerfile

  # sources environment variable configuration for our app
  env_file: ./docker/docker-application.env

  # set the build context to the root of the app
  build: .

  # makes the web container aware of the app container
  links:
    - app

  # persist SSL certificates
  volumes:
    - ssl:/var/www/ssl

  # expose the port we configured Nginx to bind to
  ports:
    - "80:80"
    - "443:443"