version: "2"
services:
    app:
        # use the Dockerfile next to this file
        build:
            context: .
            # build with Dockerfile
            dockerfile: ./.docker/containers/app/Dockerfile

        # sources environment variable configuration for our app
        env_file:
            - ./docker/docker.env
            - ./docker/containers/app/app.env
            - ./docker/containers/web/web.env

        # Reference app to /home/app (Should be copied for production)
        volumes:
            - "./app:${APP_ROOT_DIR}"
            - "./.docker/containers/app/config.js:${APP_ROOT_DIR}/config.js"
            - "./.docker/containers/app/clientConfig.js:${APP_ROOT_DIR}/client/clientConfig.js"

        # expose the port we configured for the app
        ports:
            - "${APP_PORT}"
    ghost:
        # use the Dockerfile next to this file
        build:
            context: .
            # build with Dockerfile
            dockerfile: ./.docker/containers/ghost/Dockerfile

        # sources environment variable configuration for our app
        env_file:
            - ./docker/docker.env
            - ./docker/containers/ghost/ghost.env

        volumes:
            - "ghostDB:${GHOST_CONTENT}/data"
            - "ghostImages:${GHOST_CONTENT}/images"
            - "ghostAdminAssets:${GHOST_SOURCE}/core/built/assets"
            - "ghostShared:${GHOST_SOURCE}/core/shared"
            - "./.docker/containers/ghost/config.js:${GHOST_SOURCE}/config.js"

        # expose the port we configured for ghost
        ports:
            - "${GHOST_PORT}"

    # service configuration for our web server
    web:
        # use the Dockerfile next to this file
        build:
            context: .
            # build with Dockerfile
            dockerfile: ./.docker/containers/web/Dockerfile

        # sources environment variable configuration for our app
        env_file:
            - ./docker/docker.env
            - ./docker/containers/web/web.env
            - ./docker/containers/app/app.env
            - ./docker/containers/ghost/ghost.env

        # makes the web container aware of the app container
        links:
            - app
            - ghost

        volumes:
            - "ssl:${SSL_ROOT}" # persist SSL certificates
            - "letsencryptCerts:${SSL_LE_DIR}"

        volumes_from:
            - app
            - ghost

        depends_on:
            - app
            - ghost

        # expose the port we configured Nginx to bind to
        ports:
            - "80:80"
            - "443:443"

volumes:
    ssl: {}
    letsencryptCerts: {}
    ghostDB: {}
    ghostImages: {}
    ghostAdminAssets: {}
    ghostShared: {}