version: "2"
services:
    app:
        env_file:
            - ./docker/docker.env
            - ./docker/containers/app/app.env
            - ./docker/containers/app/app.development.env

    web:
        env_file:
            - ./docker/docker.env
            - ./docker/containers/web/web.env
            - ./docker/containers/app/app.development.env